name: depup
on:
  schedule:
    - cron: '35 9 2,13,25 * *' # Runs at 9:35 UTC 2,13,25 per month
permissions:
  contents: write
  pull-requests: write

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check depup
        uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: .github/actions/vimhelp-nvcheck/Dockerfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VIM_JP_BOT_APP_ID }}
          private-key: ${{ secrets.VIM_JP_BOT_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>'
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
